import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import adminAuthRouter from "./admin-auth.js";
import customerAuthRouter from "./customer-auth.js";
import adminLocationsRouter from "./admin-locations.js";
import adminFleetRouter from "./admin-fleet.js";
import adminExtrasRouter from "./admin-extras.js";
import adminRatesRouter from "./admin-rates.js";
import adminPromosRouter from "./admin-promos.js";
import adminDiscountsRouter from "./admin-discounts.js";
import adminCustomersRouter from "./admin-customers.js";
import adminBookingsRouter from "./admin-bookings.js";
import adminDashboardRouter from "./admin-dashboard.js";
import adminTeamRouter from "./admin-team.js";
import adminRolesRouter from "./admin-roles.js";
import adminServiceRouter from "./admin-service.js";
import adminAccountingRouter from "./admin-accounting.js";
import adminFleetCalendarRouter from "./admin-fleet-calendar.js";
import adminReportsRouter from "./admin-reports.js";
import adminAlertsRouter from "./admin-alerts.js";
import adminBookingPaymentsRouter from "./admin-booking-payments.js";
import adminAuditRouter from "./admin-audit.js";
import adminParkingRouter from "./admin-parking.js";
import adminAiRouter from "./admin-ai.js";
import adminAiChatRouter from "./admin-ai-chat.js";
import adminTasksRouter from "./admin-tasks.js";
import adminFeaturedSliderRouter from "./admin-featured-slider.js";
import adminVoucherImportRouter from "./admin-voucher-import.js";
import adminMonitoringRouter from "./admin-monitoring.js";
import adminShowroomRouter from "./admin-showroom.js";
import adminStopSellRouter from "./admin-stop-sell.js";
import adminPartnersRouter from "./admin-partners.js";
import adminPartnerPayablesRouter from "./admin-partner-payables.js";
import featuredSliderRouter from "./featured-slider.js";
import storageRouter from "./storage.js";
import publicBookingsRouter from "./public-bookings.js";
import publicChatbotRouter from "./public-chatbot.js";
import locationsRouter from "./locations.js";
import fleetRouter from "./fleet.js";
import ratesRouter from "./rates.js";
import extrasRouter from "./extras.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminAuthRouter);
router.use(customerAuthRouter);
router.use(adminLocationsRouter);
router.use(adminFleetRouter);
router.use(adminExtrasRouter);
router.use(adminRatesRouter);
router.use(adminPromosRouter);
router.use(adminDiscountsRouter);
router.use(adminCustomersRouter);
router.use(adminBookingsRouter);
router.use(adminDashboardRouter);
router.use(adminTeamRouter);
router.use(adminRolesRouter);
router.use(adminServiceRouter);
router.use(adminAccountingRouter);
router.use(adminFleetCalendarRouter);
router.use(adminReportsRouter);
router.use(adminAlertsRouter);
router.use(adminBookingPaymentsRouter);
router.use(adminAuditRouter);
router.use(adminParkingRouter);
router.use(adminAiRouter);
router.use(adminAiChatRouter);
router.use(adminTasksRouter);
router.use(adminFeaturedSliderRouter);
router.use(adminVoucherImportRouter);
router.use(adminMonitoringRouter);
router.use(adminShowroomRouter);
router.use(adminStopSellRouter);
router.use(adminPartnerPayablesRouter);
router.use(adminPartnersRouter);
router.use(featuredSliderRouter);
router.use(storageRouter);
router.use(publicBookingsRouter);
router.use(publicChatbotRouter);
router.use(locationsRouter);
router.use(fleetRouter);
router.use(ratesRouter);
router.use(extrasRouter);

export default router;
