import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import adminAuthRouter from "./admin-auth.js";
import adminLocationsRouter from "./admin-locations.js";
import adminFleetRouter from "./admin-fleet.js";
import adminExtrasRouter from "./admin-extras.js";
import adminRatesRouter from "./admin-rates.js";
import adminPromosRouter from "./admin-promos.js";
import adminCustomersRouter from "./admin-customers.js";
import adminBookingsRouter from "./admin-bookings.js";
import adminDashboardRouter from "./admin-dashboard.js";
import adminTeamRouter from "./admin-team.js";
import adminServiceRouter from "./admin-service.js";
import adminAccountingRouter from "./admin-accounting.js";
import adminFleetCalendarRouter from "./admin-fleet-calendar.js";
import adminReportsRouter from "./admin-reports.js";
import adminAlertsRouter from "./admin-alerts.js";
import adminBookingPaymentsRouter from "./admin-booking-payments.js";
import adminAuditRouter from "./admin-audit.js";
import publicBookingsRouter from "./public-bookings.js";
import locationsRouter from "./locations.js";
import fleetRouter from "./fleet.js";
import ratesRouter from "./rates.js";
import extrasRouter from "./extras.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminAuthRouter);
router.use(adminLocationsRouter);
router.use(adminFleetRouter);
router.use(adminExtrasRouter);
router.use(adminRatesRouter);
router.use(adminPromosRouter);
router.use(adminCustomersRouter);
router.use(adminBookingsRouter);
router.use(adminDashboardRouter);
router.use(adminTeamRouter);
router.use(adminServiceRouter);
router.use(adminAccountingRouter);
router.use(adminFleetCalendarRouter);
router.use(adminReportsRouter);
router.use(adminAlertsRouter);
router.use(adminBookingPaymentsRouter);
router.use(adminAuditRouter);
router.use(publicBookingsRouter);
router.use(locationsRouter);
router.use(fleetRouter);
router.use(ratesRouter);
router.use(extrasRouter);

export default router;
